### ISSUE TITLE
`manual_correction.py` - output path

### ISSUE THREAD

**Issue by valosekj** [ivadomed/canproco#11]
When @mchen1110 was correcting labeling, she did not specify `-path-out` flag (because it is not mandatory). Thus, the default (`./`) output path was used. As a result, we had then difficulty to find the `derivatives` folder. 

https://github.com/ivadomed/canproco/blob/8e507365175213949a93f803221029dfdeb83301/preprocess/manual_correction.py#L66-L72

Maybe, the `-path-out` could be mandatory to explicitly ask user to specify it.

**Comment by jcohenadad** [comment]
Happy to discuss about making it mandatory, but for now, I suggest to explicitly write it in the [README](https://github.com/ivadomed/canproco/blob/main/README.md)

**Comment by valosekj** [comment]
Not planned --> script will be replaced by https://github.com/spinalcordtoolbox/manual-correction. See #17
