### ISSUE TITLE
MT has 4 dimensions for Calgary

### ISSUE THREAD

**Issue by valosekj** [ivadomed/canproco#21]
`acq-MT_MTS.nii.gz` images for the Calgary site (GE Discovery scanner) are 4D, see:

```
$ sct_image -i sub-cal056_ses-M0_acq-MT_MTS.nii.gz -header fslhd 
...
dim1		256
dim2		256
dim3		18
dim4		3
...
```

Visually, it looks that the null 3D volume represents `acq-MTon_MTS`:

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/39456460/215296535-060bd6c8-133b-4366-89c1-bc23ca1fc075.png">

The first 3D volume represents `acq-MToff_MTS`:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/39456460/215296567-ed4ebb65-bc94-4f45-bb42-8da5f8157584.png">

And the second 3D volume represents `acq-T1w_MTS`:

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/39456460/215296591-df72a83f-4ca3-4813-aea4-2c3765948d5b.png">

4D images are not optimal for processing, e.g., for the [co-registration to T2w](https://github.com/ivadomed/model_sc_centerline/blob/8eb2dbc4a7d2a69599abb650f9c32dbced79e92f/scripts/get_centerline_from_segmentation.sh#L140-L145) (which does not work for 4D images). I suggest splitting the 4D image into three individual images.

Additionally, to be compliant with the proposed derivatives conventions, I would use the [following naming](https://github.com/neuropoly/intranet.neuro.polymtl.ca/blob/jv/centralize_derivatives_convection/data/dataset-curation.md#subject-naming-convention) for the MT images:
```
acq-MTon_MTS → flip-1_mt-on_MTS
acq-MToff_MTS → flip-1_mt-off_MTS
acq-T1w_MTS → flip-2_mt-off_MTS
```

(This would also include renaming the MT images for other sites and updating the git-annex dataset)

**Comment by jcohenadad** [comment]
Good catch! Yes, this is the way to go for these data.

**Comment by valosekj** [comment]
Fixed in https://github.com/neuropoly/data-management/issues/211 --> closing this issue
