### ISSUE TITLE
`sct_analyze_lesion` requires centerline or segmentation

### ISSUE THREAD

**Issue by valosekj** [ivadomed/canproco#27]
When trying to analyze lesions using [sct_analyze_lesion](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_analyze_lesion.py), it turned out that the function requires spinal cord centerline or segmentation as a mandatory argument, see [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0e5ca305a87202465d249198aa3d4d32a32aa4e5/spinalcordtoolbox/scripts/sct_analyze_lesion.py#L47-L52). Spinal cord centerline or segmentation is not available for PSIR/STIR images, though.

Comments from the 2023-03-20 meeting:

**Short-term solution:** use SC seg from T2w, bring it to PSIR/STIR using trilinear interpolation, and use it for PSIR/STIR angle correction

**Long-term solution:** refactor [sct_analyze_lesion](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_analyze_lesion.py) function

Related `sct_analyze_lesion` refactoring effort issue:

- https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3378

**Comment by jcohenadad** [comment]
> Short-term solution: use SC seg from T2w, bring it to PSIR/STIR using trilinear interpolation, and use it for PSIR/STIR angle correction

Sounds like a reasonable strategy indeed

**Comment by valosekj** [comment]
> **Short-term solution:** use SC seg from T2w, bring it to PSIR/STIR using trilinear interpolation, and use it for PSIR/STIR angle correction

Drafted in https://github.com/ivadomed/canproco/pull/28

> **Long-term solution:** refactor [sct_analyze_lesion](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/scripts/sct_analyze_lesion.py) function

Implemented in https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4112
