### ISSUE TITLE
Optimize cord segmentation code for T2w sagittal image

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/canproco#3]
if sct_deepseg_sc does not work, try sct_propseg.

idea of workflow:
- start with sct_deepseg_sc
- run QC
- identify X % of subjects that require heavy corrction
- run another syntax on them (eg: propseg)
- run QC
- manually correct for the remaning X %

**Comment by valosekj** [comment]
To allow easy comparison of `sct_deepseg_sc` with 2d kernel, `sct_deepseg_sc` with 3d kernel and `sct_propseg`, we run all 3 segmentation methods at once across all subjects:

https://github.com/ivadomed/canproco/blob/1b1b4f8a5af37739cb83c88ffc561bc358313ec0/preprocess/sct-preprocess_data.sh#L202-L204

I then quickly checked the QC.

Conclusion:
* `sct_deepseg_sc` with 3d kernel provides the worse results 
* `sct_deepseg_sc` with 2d kernel and `sct_propseg` perform similarly. But `sct_deepseg_sc` with 2d kernel required manual corrections for fewer subjects compared to `sct_propseg`.

I identified subjects who need manual corrections; see attached zip with .yml files.

[QC_artifacts_T2w_canproco_2022-11-20.zip](https://github.com/ivadomed/canproco/files/10058133/QC_artifacts_T2w_canproco_2022-11-20.zip)

**Comment by jcohenadad** [comment]
great investigation! thank you @valosekj

**Comment by valosekj** [comment]
Done in https://github.com/ivadomed/canproco/pull/5
