### ISSUE TITLE
Add orientation-corrected-data on git annex

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/canproco#33]
When training an nnU-Net, I saw that the model was sensitive to difference in orientation between the image and the mask. With @valosekj we corrected the orientations of these images. 
I have pushed these corrections under the branch `plb/orientation-correction`. 
Who is in charge of verifications and pull requests for the git annex of canoproco ? (@jcohenadad )

Related to #29

**Comment by plbenveniste** [comment]
The concerned images are listed [here](https://github.com/ivadomed/canproco/issues/29#issuecomment-1607670842)

**Comment by jcohenadad** [comment]
> Who is in charge of verifications and pull requests for the git annex of canoproco ? (@jcohenadad )

@valosekj can you please review @plbenveniste changes?

**Comment by valosekj** [comment]
Usually, we open git-annex-related issues under https://github.com/neuropoly/data-management/issues. Examples of previous issues for canproco [here](https://github.com/neuropoly/data-management/issues?q=is%3Aissue+canproco+label%3A%22dataset%3A+canproco%22).

> > Who is in charge of verifications and pull requests for the git annex of canoproco ? (@jcohenadad )
> 
> @valosekj can you please review @plbenveniste changes?

Sure!

For the merging itself, I usually assign @mguaypaq.

**Comment by valosekj** [comment]
I "transferred" the issue to https://github.com/neuropoly/data-management/issues/252.
