### ISSUE TITLE
Orientation problem labels-disc M12 subjects

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/canproco#71]
I identified an orientation problem in the `sub-van111_ses-M12_PSIR_lesion-manual_label.nii.gz`. 

The dimension is : (16, 336, 336) instead of (336, 336,16)

→ Currently investigating how to solve and if other files have the same problems

The files come from "Discs labelling Hourglass" 

tagging @NathanMolinier @valosekj

**Comment by valosekj** [comment]
Good catch!

The original PSIR image looks good (it has `336, 336, 16` dimensions; which also corresponds with M0):

```console
valosek@macbook-pro:~/data/data.neuro.polymtl.ca/canproco/sub-van111$ sct_image -i ses-M12/anat/sub-van111_ses-M12_PSIR.nii.gz -header | grep "dim"
dim		[3, 336, 336, 16, 1, 1, 1, 1]

valosek@macbook-pro:~/data/data.neuro.polymtl.ca/canproco/sub-van111$ sct_image -i ses-M0/anat/sub-van111_ses-M0_PSIR.nii.gz -header | grep "dim" 
dim		[3, 336, 336, 16, 1, 1, 1, 1]
```

Maybe the disc labeling was done on the reoriented image? If so, try to reorient `sub-van111_ses-M12_PSIR_lesion-manual_label.nii.gz` to the PSIR native orientation (`AIL`).

**Comment by NathanMolinier** [comment]
Indeed the images were reoriented before creating the labels and I forgot to reuse the original orientation of the image.

However, it is a good reminder that we always need to make sure that we check the orientation before treating an image. The class [Image](https://github.com/ivadomed/utilities/blob/main/scripts/image.py) (from SCT) is suited for this task.

**Comment by valosekj** [comment]
Okay, I see! Could you please reorient the disc labels back to the original orientation and push them to git-annex?

**Comment by plbenveniste** [comment]
This was solved during the re-orientation of all derivatives file in this issue : https://github.com/ivadomed/ms-lesion-agnostic/issues/1#issuecomment-1949222474
