### ISSUE TITLE
Rename model on github's asset

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/canproco#74]
On "https://github.com/ivadomed/canproco/releases/tag/r20240125", the name "Dataset222_RegionBasedLesionSeg.zip" is misleading as people might think it is a dataset (instead of a model).

I suggest naming the model something like: "model_ms_seg_sc-lesion_regionBased.zip" or something like this (inspired by [our conventions](https://github.com/ivadomed/ivadomed/wiki/repositories))

**Comment by plbenveniste** [comment]
Done ! The model was renamed to the above-suggested name.
