### ISSUE TITLE
Suggestions on the README

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/canproco#79]
- Add TOC
- move the 'requirements' inside the section that requires the requirements
- clarify what the section Preprocessing is for (if this is for creating the manual segmentation, then, there should be parent section called "manual lesion segmentation", and the preprocessing section should go in it);

after discussion, we decided to change the landing page so that it is up front clear that this repos is a collection of sub-projects, and list as bullet points the various sub-projects (eg: redirect to the README of the children folders)

assigne @jcohenadad as reviewer for the PR

**Comment by plbenveniste** [comment]
Cleaning was done in PR #80.  We removed some sections which weren't useful, but which can still be accessed from previous releases.
