### ISSUE TITLE
Redirect to SCT for SC segmentation with contrast agnostic

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/canproco#81]
Now that the contrast agnostic model is available in SCT 6.2+, we should redirect to it in https://github.com/ivadomed/canproco/blob/plb/cleaning_canproco/segment_sc_contrast-agnostic/README.md

related to #80

**Comment by plbenveniste** [comment]
The folder was removed on branch `plb/cleaning_canproco` because it wasn't used anymore.
