### ISSUE TITLE
Suggestion to change `exclude.yml` file format

### ISSUE THREAD

**Issue by plbenveniste** [ivadomed/canproco#83]
I want to propose an alternative format for the `exclude.yml` file.
Here is the current format
```console
# t2w
- sub-cal088_ses-M0   # Poor data quality
- sub-cal209_ses-M0   # Missing T2w file
# PSIR
- sub-mon006_ses-M12
```
Proposed format:
```console
# t2w
- sub-cal088_ses-M0_T2w   # Poor data quality
- sub-cal209_ses-M0 _T2w  # Missing T2w file
# PSIR
- sub-mon006_ses-M12_PSIR
```

The reason for this change, is that when we load the data from the config file this way : 
```console
with open(exclude_list, 'r') as file:
    exclude_list = yaml.safe_load(file)
```
What we have is : `[sub-cal088_ses-M0, sub-cal209_ses-M0, sub-mon006_ses-M12]`
And there we don't have the information of what should contrast are concerned. 
With the new convention, we directly know which files to avoid. 

What do you think @jcohenadad @NathanMolinier @valosekj ?

**Comment by valosekj** [comment]
Thanks for posting this out!

The issue here is that we use `#` to define keys. Which is incorrect; `#` is intended for comments. To define YAML keys, we can simply write  `t2w:`, for example:

```yml
t2w:
- sub-cal088_ses-M0   # Poor data quality
- sub-cal209_ses-M0   # Missing T2w file
PSIR:
- sub-mon006_ses-M12
```

Then, the YAML file is loaded as a dict with contrasts as keys:

```python
file='exclude.yml'
with open(file, 'r') as stream:
    dict_exclude_subj = yaml.safe_load(stream)

dict_exclude_subj
{'t2w': ['sub-cal088_ses-M0', 'sub-cal209_ses-M0'], 'PSIR': ['sub-mon006_ses-M12']}

dict_exclude_subj['t2w']
['sub-cal088_ses-M0', 'sub-cal209_ses-M0']
```

**Comment by plbenveniste** [comment]
Thanks for your input @valosekj. 
I will update the exclude file with your proposed convention.

**Comment by plbenveniste** [comment]
Fixed on main branch !

**Comment by valosekj** [comment]
> Fixed on main branch !

Thank you!
